### ISSUE TITLE
[SUGGESTION] Mob spawn rates

### ISSUE THREAD

**Issue by srnyx** [PheonixVX/fof#2]
I feel like the mob spawn rates are super high, would be nice if we could lower them with a config file or something.

It'd also be nice if the hostile mobs only spawned at night and not all the time.

**Comment by PhoenixVX** [comment]
Latest commit as of now (https://github.com/PheonixVX/fof/commit/41a388c66170789085e350f69833fe30c20bdeef) adds a config. Won't close until I fix the mobs spawning at all times of the day.

**Comment by PhoenixVX** [comment]
Mobs spawning at daytime should be fixed now. Re-open if the issue persists.
