### ISSUE TITLE
Reference map could not be read

### ISSUE THREAD

**Issue by srnyx** [PheonixVX/fof#3]
Getting this error on startup (server):
`[15:30:01] [main/WARN]: Reference map 'FOF-refmap.json' for FOF.mixins.json could not be read. If this is a development environment you can ignore this message`

**Comment by PhoenixVX** [comment]
So... I am extremely sorry for not even seeing these issues. Github committed a huge flop and didn't notify me at all. These issues seem pretty easy to fix though.

**Comment by srnyx** [comment]
> So... I am extremely sorry for not even seeing these issues. Github committed a huge flop and didn't notify me at all.

It's all good! There's no rush haha

**Comment by PhoenixVX** [comment]
Also, If you do want to contact me in a much more timely fashion, join my discord: https://discord.gg/kvz49Kh4KE

**Comment by srnyx** [comment]
> Also, If you do want to contact me in a much more timely fashion, join my discord: https://discord.gg/kvz49Kh4KE

Do you happen to be in The Fabric Project Discord server?

**Comment by PhoenixVX** [comment]
I do happen to be in the Fabric Project discord server.

**Comment by PhoenixVX** [comment]
Should be fixed in #004f7dd. Let me know if it's not fixed.

**Comment by srnyx** [comment]
> Should be fixed in #004f7dd. Let me know if it's not fixed.

Not fixed:
```[19:33:10] [main/WARN]: Reference map 'FOF-refmap.json' for FOF.mixins.json could not be read. If this is a development environment you can ignore this message```
