### ISSUE TITLE
Eldritch Gown erroring entity

### ISSUE THREAD

**Issue by srnyx** [PheonixVX/fof#9]
Whenever the Eldritch Gown tries to attack, a mod I'm using removes it (so that the server doesn't crash): https://paste.srnyx.xyz/weluhebugu.properties

**Comment by PhoenixVX** [comment]
Duplicate of issue #8

**Comment by PhoenixVX** [comment]
That should be fixed in the latest commit. Try that and report back

**Comment by srnyx** [comment]
I've recently shutdown my modded server.
This also means I'm leaving a majority of the Fabric/modded community. Sorry if this causes any complications.
